name: acileko
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1  # Güncel sürüm
  firebase_core: ^3.9.0                 # Güncel sürüm
  firebase_auth: ^5.3.4                 # Güncel sürüm
  firebase_messaging: ^15.1.6           # Güncel sürüm
  http: ^1.2.2                          # HTTP request
  path_provider: ^2.1.5                 # Uyumluluk için uygun sürüm
  cloud_firestore: ^5.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0                 # Güncel sürüm

flutter:
  uses-material-design: true
  assets:
    - assets/config.json  # JSON dosyasını burada dahil ettik
